# Site/SEO settings
email: us@daamireview.com
baseurl: "www.daamireview.com"
permalink: /:year/:month/:day/:title/
google_analytics: 

name: DaamiReview
title: DaamiReview
description: >
  DaamiReview stands to just blab about the movies that we have seen
url:
twitter_username: daamireview
default_img: /assets/images/seo.jpg
social:

  - name: Twitter
    url: https://twitter.com/DaamiReview
  - name: Instagram
    url: https://www.instagram.com/daamireview/
  - name: Facebook
    url: https://www.facebook.com/daami.review.3
  - name: YouTube
    url: https://www.youtube.com/channel/UC_0ezAIoT768C1C_Xa2IeWw/
  - name: Codepen
    url: https://codepen.io/daamireview

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://daamireview.us18.list-manage.com/subscribe/post?u=83cd049598bdcd3a129422398&amp;id=e8d0e99897
mailchimp_input: b_83cd049598bdcd3a129422398_e8d0e99897

# Author settings
author:
  - name: Daami Review Team
    bio: HerekoChau stands to just blab about the movies that we have seen.
    url: http://www.daamireview.com

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'DaamiReview'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-youtube
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
